### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by DawidSzpejna** [engineer-boys/espert-core#2]
I don't have energy at now to format everything that's why there are some mistakes: 
- There is used `EP` prefix >> The prefix `Esp` should be used
- There is used `Esper` >> The name `Espert` should be used
- There is `ContextApplication` >> The name should be `ApplicationContext`
- There is no file with format settings... because i couldn't decided what format is the best and i was exhausted :(

**Comment by kubo11** [comment]
Everything but file with formating settings is done.

**Comment by kubo11** [comment]
All done
